copy /Y c:\_LUA_\LAPI.H LUA\
copy /Y c:\_LUA_\LAPI.CPP LUA\
copy /Y c:\_LUA_\LAUXLIB.H LUA\
copy /Y c:\_LUA_\LAUXLIB.CPP LUA\
copy /Y c:\_LUA_\LBASELIB.CPP LUA\
copy /Y c:\_LUA_\LCODE.H LUA\
copy /Y c:\_LUA_\LCODE.CPP LUA\
copy /Y c:\_LUA_\LCOROLIB.CPP LUA\
copy /Y c:\_LUA_\LCTYPE.H LUA\
copy /Y c:\_LUA_\LCTYPE.CPP LUA\
copy /Y c:\_LUA_\LDBLIB.CPP LUA\
copy /Y c:\_LUA_\LDEBUG.H LUA\
copy /Y c:\_LUA_\LDEBUG.CPP LUA\
copy /Y c:\_LUA_\LDO.H LUA\
copy /Y c:\_LUA_\LDO.CPP LUA\
copy /Y c:\_LUA_\LDUMP.CPP LUA\
copy /Y c:\_LUA_\LFUNC.H LUA\
copy /Y c:\_LUA_\LFUNC.CPP LUA\
copy /Y c:\_LUA_\LGC.H LUA\
copy /Y c:\_LUA_\LGC.CPP LUA\
copy /Y c:\_LUA_\LINIT.CPP LUA\
copy /Y c:\_LUA_\LIOLIB.CPP LUA\
copy /Y c:\_LUA_\LLEX.H LUA\
copy /Y c:\_LUA_\LLEX.CPP LUA\
copy /Y c:\_LUA_\LMATHLIB.CPP LUA\
copy /Y c:\_LUA_\LMEM.H LUA\
copy /Y c:\_LUA_\LMEM.CPP LUA\
copy /Y c:\_LUA_\LOADLIB.CPP LUA\
copy /Y c:\_LUA_\LOBJECT.H LUA\
copy /Y c:\_LUA_\LOBJECT.CPP LUA\
copy /Y c:\_LUA_\LOPCODES.H LUA\
copy /Y c:\_LUA_\LOPCODES.CPP LUA\
copy /Y c:\_LUA_\LOSLIB.CPP LUA\
copy /Y c:\_LUA_\LPARSER.H LUA\
copy /Y c:\_LUA_\LPARSER.CPP LUA\
copy /Y c:\_LUA_\LSTATE.H LUA\
copy /Y c:\_LUA_\LSTATE.CPP LUA\
copy /Y c:\_LUA_\LSTRING.H LUA\
copy /Y c:\_LUA_\LSTRING.CPP LUA\
copy /Y c:\_LUA_\LSTRLIB.CPP LUA\
copy /Y c:\_LUA_\LTABLE.H LUA\
copy /Y c:\_LUA_\LTABLE.CPP LUA\
copy /Y c:\_LUA_\LTABLIB.CPP LUA\
copy /Y c:\_LUA_\LTM.H LUA\
copy /Y c:\_LUA_\LTM.CPP LUA\
copy /Y c:\_LUA_\LUA.H LUA\
copy /Y c:\_LUA_\LUA.HPP LUA\
copy /Y c:\_LUA_\LUALIB.H LUA\
copy /Y c:\_LUA_\LUNDUMP.H LUA\
copy /Y c:\_LUA_\LUNDUMP.CPP LUA\
copy /Y c:\_LUA_\LUTF8LIB.CPP LUA\
copy /Y c:\_LUA_\LVM.H LUA\
copy /Y c:\_LUA_\LVM.CPP LUA\
copy /Y c:\_LUA_\LZIO.H LUA\
copy /Y c:\_LUA_\LZIO.CPP LUA\
copy /Y c:\_LUA_\lprefix.h LUA\
copy /Y c:\_LUA_\luaconf.h LUA\
copy /Y c:\_LUA_\llimits.h LUA\
